name: Run test VS

on:
  push:
    branches: [ develop, update_libraries ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        define:
          - ""
          - "-DBASE_MATRIX_USE_STD_VECTOR"
          - "-DBASE_MATRIX_USE_FOR_LOOP_OPERATION"
          - "-DBASE_MATRIX_USE_STD_VECTOR -DBASE_MATRIX_USE_FOR_LOOP_OPERATION"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build and Run C++ application
      run: |
        g++ -std=c++11 -Wall ${{ matrix.define }} -I ./python_numpy -I ./base_matrix -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/base_utility_cpp/base_utility -I ./test_vs/MCAP_tester/include -o ./test_vs/app ./test_vs/test_vs_main.cpp && ./test_vs/app
