name: Run test VS

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build C++ application
      run: |
        g++ -std=c++11 -I ./python_numpy -I ./base_matrix -I ./test_vs/MCAP_tester/include -o ./test_vs/app ./test_vs/test_vs_main.cpp

    - name: Run the application
      run: |
        ./test_vs/app

    - name: activate std::vector use option
      run: |
        sed -i 's@// #define USE_STD_VECTOR@#define USE_STD_VECTOR@g' ./base_matrix/base_matrix_macros.hpp

    - name: Build C++ application
      run: |
        g++ -std=c++11 -I ./python_numpy -I ./base_matrix -I ./test_vs/MCAP_tester/include -o ./test_vs/app ./test_vs/test_vs_main.cpp

    - name: Run the application
      run: |
        ./test_vs/app